[package]
name = "diffvg-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
cubecl = { version = "0.9.0", default-features = false, features = ["std", "wgpu"] }
image = { version = "0.25.5", default-features = false, features = ["png", "gif"] }
